name: Build Install Script

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic changes
          branch: main
          file_pattern: '*.sh'
